// import { Inter } from 'next/font/google'
// import './globals.css'
// import Layout from '@/components/layout/Layout'


// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <Layout>
//       <body className={inter.className}>{children}</body>
//       </Layout>
//     </html>
//   )
// }


import MainNavigation from '../components/layout/MainNavigation';
import classes from '../components/layout/Layout.module.css';

function Layout(props) {
  return (
    <div>
      <MainNavigation />
      <main className={classes.main}>{props.children}</main>
    </div>
  );
}

export default Layout;
